export const ActionTypes = {
    SET_AIRPORTS: "SET_AIRPORTS",
    SET_AIRLINES: "SET_AIRLINES",
    SET_FLIGHT_RESULTS: "SET_FLIGHT_RESULTS",
    SET_FILTERED_FLIGHT_RESULTS: "SET_FILTERED_FLIGHT_RESULTS",
    SET_SELECTED_FLIGHT_OFFER: "SET_SELECTED_FLIGHT_OFFER",
    SET_FLIGHT_REQUEST_META: "SET_FLIGHT_REQUEST_META",
    SET_LOGIN_CREDENTIALS: "SET_LOGIN_CREDENTIALS",
    DELETE_LOGIN_CREDENTIALS: "DELETE_LOGIN_CREDENTIALS",
    DELETE_FLIGHT_RESULTS: "DELETE_FLIGHT_RESULTS",
    FETCH_ARTICLES: "FETCH_ARTICLES"
};